### ISSUE TITLE
Cannot work out the change with 0.2.0

### ISSUE THREAD

**Issue by cabbiepete** [deepsweet/mocku#3]
I feel like this is likely an understanding issue on my part but am struggling with it so felt like others might do the same and so worth a issue. Maybe end up providing a documentation item from this discussion.

Code below works with 0.1.2

```
import(modulePath)
      .then((route) => {
        // Bind our application to the router
        app.use('/', route.default);
       })
```

And I'm not sure if it requires any changes for 0.2.0 but once I update I start a bunch of errors

```
SyntaxError: Missing export 'default' in ES module:
```

Where ever I use mocku.

Thanks in advance

**Comment by deepsweet** [comment]
Oh, sorry, I've totally missed this issue. There is a breaking change with v0.2.0, I started to define mock objects as ES Modules with `__esModule: true`, so mock is a valid ESM from the loader perspective and not just a plain object.

```js
mock('./file', {
  './file2': {
    default: 'file2'
  }
)

import('./file')
  .then((namespace) => {
    console.log(namespace)
    // before: { default: { default: 'file2' } }
    // now: { default: 'file2' }
  }})
  .catch(console.error)
```

Could you please provide more code, especially the mocking part? What's inside of `route` before and after v0.2.0?

**Comment by deepsweet** [comment]
I've just faced the same by myself:

Error:

```js
mock('../src/', {
  delay: delayStub
})
```

Works:

```js
mock('../src/', {
  delay: {
    default: delayStub
  }
})
```

Please re-open the issue if your case is different and the error still occurs.

**Comment by cabbiepete** [comment]
Sorry to not get back to you @deepsweet I'll try the change and let you know if any issue. Have a few things in the list. Thanks again for the info.

**Comment by cabbiepete** [comment]
@deepsweet This approach worked for me. Initially I did not like the boilerplate feel but it is very explicit about what a ES6 module is. On reflection it seems like a good change to get in at this early stage.

As we build out more of this pattern in the code we are using if we come up with a nice helper pattern I'll share. We need a lot more examples before that is worth it thought I think, let me know if you disagree.

**Comment by deepsweet** [comment]
This boilerplate feel is how dynamic ESM imports actually works – you get a "namespace object" including `default` as a property instead of result directly:

```js
const { default: lib } = await import('lib')
```

I hope that changes in v0.2.0 just aligned everything properly, exactly in order to avoid any confusion :)

**Comment by cabbiepete** [comment]
@deepsweet Exactly agree entirely.
